import cv2
import matplotlib.pyplot as plt
img0=cv2.imread("D:/rah-310/OIP.jfif")
gray=cv2.cvtColor(img0,cv2.COLOR_BGR2GRAY)
img=cv2.GaussianBlur(gray,(3,3),0)
laplacian=cv2.Laplacian(img,cv2.CV_64F)
soblex=cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
sobley=cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
plt.subplot(2,2,1),plt.imshow(img,cmap='gray')
plt.title('Original image'),plt.xticks([]),plt.yticks([])
plt.subplot(2,2,2),plt.imshow(laplacian,cmap='gray')
plt.title('Laplacian'),plt.xticks([]),plt.yticks([])
plt.subplot(2,2,3),plt.imshow(soblex,cmap='gray')
plt.title('sobel-x detection'),plt.xticks([]),plt.yticks([])
plt.subplot(2,2,4),plt.imshow(sobley,cmap='gray')
plt.title('sobel-y detection'),plt.xticks([]),plt.yticks([])
plt.show()